#!/usr/bin/env bash

imageName="grisu48/orion:latest"
containerName=gemini-server
localConfroot=$(pwd)"/conf"
localWebroot=$(pwd)"/static"

case $1 in
  gen|generate)
    # remove static content
    rm static/*.gmi
    rm static/journal/*.gmi
    # avoid clutter
    rm pages/journal/2*.tmpl
    rm partials/journal-entries.partial

    # build templates for each journal entry and a .gmi from those
    awk -f scripts/journal-entries.awk
    # build the journal index
    awk -f scripts/journal-index.awk
    awk -f scripts/journal-latest.awk
    # build all "main" pages
    awk -f scripts/pages.awk
    ;;
  start)
    docker run -d --name $containerName \
      --volume $localConfroot:/conf:ro \
      --volume $localWebroot:/data:ro \
      --rm -p 1965:1965 $imageName
    ;;
  stop)
    docker stop $containerName
    ;;
  update)
    git pull
    ;;
  *) 
    echo "Usage $0 (gen(erate)|start|stop|update)"
    exit 1;
    ;;
esac

