#!/usr/bin/env bash

imageName="grisu48/orion:latest"
containerName=orion
localConfroot=$(pwd)"/conf"
localWebroot=$(pwd)"/static"

case $1 in
  gen|generate)
    # avoid clutter
    rm pages/journal/*.tmpl
    rm static/journal/*.gmi
    # build templates for each entry and a .gmi from those
    awk -f scripts/journal-entries.awk
    # build the journal index
    awk -f scripts/journal-index.awk
    awk -f scripts/journal-latest.awk
    # build all "main" pages
    awk -f scripts/pages.awk
    ;;
  start)
    docker run -d --name $containerName \
      --volume $localConfroot:/conf:ro \
      --volume $localWebroot:/data:ro \
      --rm -p 1965:1965 $imageName
    ;;
  stop)
    docker stop $containerName
    ;;
  *) 
    echo "Usage $0 (gen(erate)|start|stop)"
    exit 1;
    ;;
esac

